kind: Service
apiVersion: v1
metadata:
  name: docker-kubernetes-service
spec:
  type: LoadBalancer
  selector:
    app: docker-kubernetes
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8085
