apiVersion : apps/v1
kind: Deployment
metadata:
  name: "sskubecluster-071a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "sskubecluster-071a"
  template:
    metadata:
      labels:
        app: "sskubecluster-071a"
    spec:
      containers:
        - name: "sskubecluster-071a"
          image: "sskubereg.azurecr.io/sskubecluster"
          ports:
          - containerPort: 8085