apiVersion: v1
kind: Service
metadata:
    name: "sskubecluster-071a"
    labels:
        app: "sskubecluster-071a"
spec:
    type: LoadBalancer
    ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
    selector:
        app: "sskubecluster-071a"