on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n sskubecr -g sskubecrb94c-rg --location "North Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n sskubecr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n sskubecr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n sskubecr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: sskubecr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t sskubecr.azurecr.io/sskubecluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push sskubecr.azurecr.io/sskubecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_sskubecluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ss-kube-ns | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace ss-kube-ns`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: ss-kube-ns
        container-registry-url: sskubecr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: sskubeclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ss-kube-ns
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          sskubecr.azurecr.io/sskubecluster:${{ github.sha }}
        imagepullsecrets: |
          sskubeclustedockerauth   
